### ISSUE TITLE
无法加载图片

### ISSUE THREAD

**Issue by Nexvrek** [QingXia-Ela/reclamation-algorithm-map#1]
从打开标签页，排除了网络问题后约10min左右，地图背景没有加载（默认黑色），关卡地图没有加载（有img标签，但对应图片似乎有问题）
地图正常加载
关卡描述正常加载
相关素材，天气，资源区资源贴图正常加载。

![image](https://github.com/QingXia-Ela/reclamation-algorithm-map/assets/42509569/a19d67fb-9e79-436e-93d2-6853270021be)

如果说是开发环境需要长时间等待建议给一个参考时间🙏

**Comment by QingXia-Ela** [comment]
网络有显示请求了图片吗，状态码是什么。开发环境下所有的图都应该是秒出的，可能就关卡地图稍微要等一下，因为是直接从b站获取的图，其余的图都不应该有问题

**Comment by QingXia-Ela** [comment]
如果发现浏览器正常请求图片，请告诉我您使用的浏览器版本，可能是您的浏览器不支持avif图片格式，这种问题后续会修复

**Comment by Nexvrek** [comment]
> 网络有显示请求了图片吗，状态码是什么。开发环境下所有的图都应该是秒出的，可能就关卡地图稍微要等一下，因为是直接从b站获取的图，其余的图都不应该有问题

background-QZDM6Mch.avif  status:206（不过背景依旧是纯黑，在本地打开装了对应扩展后可以正常浏览图片）

**Comment by Nexvrek** [comment]
> 如果发现浏览器正常请求图片，请告诉我您使用的浏览器版本，可能是您的浏览器不支持avif图片格式，这种问题后续会修复

浏览器信息：Microsoft Edge
版本 119.0.2151.97 (正式版本) (64 位)

**Comment by Nexvrek** [comment]
> > 如果发现浏览器正常请求图片，请告诉我您使用的浏览器版本，可能是您的浏览器不支持avif图片格式，这种问题后续会修复
> 
> 浏览器信息：Microsoft Edge 版本 119.0.2151.97 (正式版本) (64 位)

没事了，更新到122.0.2365.80 (正式版本) (64 位)后就没问题了......
